#!/bin/bash
echo "Which user would you like to delete?"
read username

red='tput setaf 1'
green='tput setaf 2'
reset='tput sgr0'

check_user='cat /etc/passwd | grep $username'
if [ "$check_exist" != "$NULL" ]; then
	sudo passwd -l $username
	if [ "$(pgrep -u $username)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $username)
	fi
	sudo userdel -r $username
	echo "${green}user was deleted"
else
	echo "${red}user doesn't exist"
fi
